//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEOAnalyzer {
	
	
	public partial class _Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox textStopWords;
		
		protected System.Web.UI.WebControls.CheckBox checkBoxCalculateWordsOnPage;
		
		protected System.Web.UI.WebControls.CheckBox checkBoxCalculateKeywordsOnPage;
		
		protected System.Web.UI.WebControls.CheckBox checkBoxCalculateExternalLinks;
		
		protected System.Web.UI.HtmlControls.HtmlInputRadioButton radioAnalyzeUrl;
		
		protected System.Web.UI.HtmlControls.HtmlInputRadioButton radioAnalyzeText;
		
		protected System.Web.UI.WebControls.Label labelErrorText;
		
		protected System.Web.UI.WebControls.TextBox textUrlOrText;
		
		protected System.Web.UI.WebControls.Button buttonAnalyze;
		
		protected System.Web.UI.WebControls.Label labelExternalLinkNumber;
		
		protected System.Web.UI.WebControls.GridView gridViewWords;
		
		protected System.Web.UI.WebControls.GridView gridViewKeywords;
	}
}
